Repository srinivas-poturi-3/templates, pull requests merged in 2023-12, with the labels that each got.

#4 Added PR label check workflow
  .github/workflows/my-new-workflow.yaml
  .github/workflows/pr-label-check.yaml
Labels: enhancement

#7 created version api
  .github/workflows/my-new-workflow.yaml
  .github/workflows/pr-label-check.yaml
  .gitignore
  Dockerfile
  README.md
  go.mod
  go.sum
  internal/api/v1.go
  internal/api/version.go
  internal/logs/logs.go
  internal/pkg/app/app.go
  internal/pkg/app/errors.go
  internal/pkg/app/run.go
  internal/pkg/app/run_test.go
  internal/server/server.go
  main.go
  swagger/v1/README.md
  swagger/v1/generate.go
  swagger/v1/paths/version.yaml
  swagger/v1/schemas/version.yaml
  swagger/v1/server.generated.go
  swagger/v1/server.yaml
  swagger/v1/swagger-bundle.yaml
  swagger/v1/types.generated.go
  templates/terraform/Create-EC2.tf
Labels: enhancement

#8 created version api
  .github/workflows/pr-label-check.yaml
Labels: enhancement

#10 Added version while building image
  .github/release.yaml
  .github/workflows/my-new-workflow.yaml
  .github/workflows/pr-label-check.yaml
  Dockerfile
  go.mod
  internal/api/version.go
  internal/pkg/app/run.go
  internal/server/server.go
  main.go
Labels: enhancement

#13 Br 3 (#12)
  .github/workflows/deploy-test.yaml
Labels: enhancement, devops

#16 Br 3
  .github/workflows/deploy-test.yaml
Labels: documentation

#17 Br 3 (#16)
  .github/workflows/deploy-test.yaml
Labels: enhancement, devops

#23 Br 3
  .github/workflows/deploy-test.yaml
Labels: devops

#24 created a workflow to deploy tag into registry
  .github/workflows/deploy-tag.yaml
Labels: enhancement, devops

#25 created a workflow to deploy tag into registry
  .github/workflows/deploy-tag.yaml
Labels: enhancement

#26 created a workflow to deploy tag into registry
  .github/workflows/deploy-tag.yaml
Labels: devops

#27 created a workflow to deploy tag into registry
  .github/workflows/deploy-tag.yaml
  .github/workflows/my-new-workflow.yaml
Labels: devops
